# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41a08689457a1cc289e962e144fab9cd4e4f92c398edf3365ed50dcbb22eb38ebdfcc5029f6ae71472f233f020679763e7033f3d864c12b8be39f0499589ecb5

test:
  secret_key_base: f6ec304ba503efbfe5f05302e7b64f151955854d978c03c5a459a300a3cdfcd6b294f334297f972e65c458ca42b3a15892f128f2a58c969ff5bbceca37545f77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
